# Site Settings
title: Marin Luketin
url: 'http://mluketin.github.io'
baseurl: '/' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Marin Luketin
tagline: Software Developer
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I am a master student at the University of Zagreb, Faculty of Electrical Engineering and Computing, Croatia.
This semester I am working on my Master Thesis at EPFL, Switzerland at CHILI Lab. (you can see project 
I am working on under the project sections of this page). I started working as a student in November 2015. For the last two years 
I have been working at Ericsson on a real-time communication platform. I have a general interest in programming and software development.
I love programming and creating something weather it is mobile, web, desktop or server application. 
I am also interested in new technologies and languages. 
If you have any questions for me, please do not hesitate to contact me.'

#sidebar links
email: marin.luketin@gmail.com
#phone: 012 345 6789
#website: blog.webjeda.com #do not add http://
linkedin: marin-luketin
github: mluketin
#twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
#analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
