# Site Settings
title: Marin Luketin
url: 'http://mluketin.github.io'
baseurl: '/' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Marin Luketin
tagline: Software Engineer
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I am a software engineer working for holo|one since October 2018. I worked for two years in Ericsson, Zagreb, before I moved to Switzerland. 
I finished my master studies at University of Zagreb, Croatia (Jul 2018). 
I did my master thesis at EPFL, Switzerland, in Spring semester 2018.'

#sidebar links
email: marin.luketin@gmail.com
phone: +41 77 927 06 54
#phone: +385 91 182 4630
#website: blog.webjeda.com #do not add http://
linkedin: marin-luketin
github: mluketin
#twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
#analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
